// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfafUGHkfgY-ZvX3WM5eydeZ-GyIMt9M',
    appId: '1:19522211965:android:6cc13974e40d9d1e286114',
    messagingSenderId: '19522211965',
    projectId: 'color-calendar-750f5',
    databaseURL: 'https://color-calendar-750f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'color-calendar-750f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy5ptSjPs7YEQgvFCLph2w_JC27rCW3g0',
    appId: '1:19522211965:ios:afcf1b1440211b65286114',
    messagingSenderId: '19522211965',
    projectId: 'color-calendar-750f5',
    databaseURL: 'https://color-calendar-750f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'color-calendar-750f5.appspot.com',
    androidClientId: '19522211965-v2k32843a9fkc2bnosbbkias1keacao0.apps.googleusercontent.com',
    iosClientId: '19522211965-mr86j0djvbitv3b7um6iq01or24qrob5.apps.googleusercontent.com',
    iosBundleId: 'io.github.vilginushki.colorCalendar',
  );
}
